// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package fulfillment

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FulfillmentIntegrationServiceClient is the client API for FulfillmentIntegrationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FulfillmentIntegrationServiceClient interface {
	// ListNeedToShip returns fulfillment orders you owe a shipment on: work
	// routed to your warehouses and not yet shipped or cancelled.
	//
	// New work and re-routed work look the same here, which is the point. A
	// partial re-route reduces a line's quantity rather than removing the
	// fulfillment order, so `lines` is authoritative on every read and must not
	// be cached across polls.
	//
	// An order leaves this queue when its lines are shipped, when Zentail
	// cancels it, or when you reject it. Acknowledging does not remove it — you
	// still owe the shipment.
	ListNeedToShip(ctx context.Context, in *ListNeedToShipRequest, opts ...grpc.CallOption) (*ListNeedToShipResponse, error)
	// ListNeedToCancel returns fulfillment orders you have acknowledged that
	// Zentail now wants pulled back — re-routed to another warehouse, or
	// cancelled by the buyer or the channel.
	//
	// Only acknowledged work appears here. If you never told Zentail you had
	// created it, there is nothing on your side to undo and the units simply
	// leave ListNeedToShip.
	//
	// A partial cancellation puts the same fulfillment order in **both** queues:
	// cancel the quantities named here, ship what ListNeedToShip still shows.
	ListNeedToCancel(ctx context.Context, in *ListNeedToCancelRequest, opts ...grpc.CallOption) (*ListNeedToCancelResponse, error)
	// GetFulfillmentOrder fetches one fulfillment order, whatever queue it is or
	// is not in. For troubleshooting and for reconciling after a crash.
	GetFulfillmentOrder(ctx context.Context, in *GetFulfillmentOrderRequest, opts ...grpc.CallOption) (*FulfillmentOrder, error)
	// AcknowledgeFulfillmentOrders records the identifier you gave the work on
	// your own side. It does **not** drain ListNeedToShip — you still owe the
	// shipment — and it is not required before shipping.
	//
	// Two reasons to call it. It is how a crash between "created it on my side"
	// and "told Zentail" becomes recoverable: the fulfillment order is still in
	// ListNeedToShip, and the absence of your id there tells you to reconcile
	// before creating a duplicate. And it is what puts the work into
	// ListNeedToCancel if Zentail later needs it pulled back.
	AcknowledgeFulfillmentOrders(ctx context.Context, in *AcknowledgeFulfillmentOrdersRequest, opts ...grpc.CallOption) (*AcknowledgeFulfillmentOrdersResponse, error)
	// ConfirmShipments reports packages that have shipped, draining the shipped
	// quantities from ListNeedToShip.
	//
	// Idempotent on external_shipment_id: replaying a shipment is a no-op, so a
	// retry after a timeout can never double-ship.
	ConfirmShipments(ctx context.Context, in *ConfirmShipmentsRequest, opts ...grpc.CallOption) (*ConfirmShipmentsResponse, error)
	// ConfirmCancellations reports that you have pulled work back on your side,
	// draining it from ListNeedToCancel.
	//
	// Confirm only what you actually cancelled. If a unit has already shipped and
	// cannot be recalled, say so with `already_shipped` rather than confirming —
	// Zentail needs to know the difference to keep the customer order right.
	ConfirmCancellations(ctx context.Context, in *ConfirmCancellationsRequest, opts ...grpc.CallOption) (*ConfirmCancellationsResponse, error)
	// RejectFulfillmentOrders tells Zentail you cannot fulfil work it asked for —
	// out of stock, damaged, address undeliverable. This is the other direction
	// from ConfirmCancellations: there, Zentail asked; here, you are declining.
	//
	// Zentail reroutes the work or surfaces it to the user, and it leaves
	// ListNeedToShip.
	RejectFulfillmentOrders(ctx context.Context, in *RejectFulfillmentOrdersRequest, opts ...grpc.CallOption) (*RejectFulfillmentOrdersResponse, error)
	// RaiseAlerts raises alerts against fulfillment orders, using the same alert
	// model the rest of Zentail already shows on a customer order.
	//
	// Idempotent by design: Zentail refuses a second open alert of the same type
	// on the same order, so a poller can raise the same condition every pass
	// without creating noise. No client-side "have I already alerted?"
	// bookkeeping.
	//
	// An alert is not a substitute for rejecting. Raise one to explain a delay;
	// reject when you are not going to ship.
	RaiseAlerts(ctx context.Context, in *RaiseAlertsRequest, opts ...grpc.CallOption) (*RaiseAlertsResponse, error)
	// ResolveAlerts resolves alerts **this integration raised**, recording why.
	//
	// Scoping matters: an alert of the same type raised by Zentail itself, or by
	// another integration, on the same order survives. Resolving by type alone
	// would let one caller silently clear another's alerts.
	ResolveAlerts(ctx context.Context, in *ResolveAlertsRequest, opts ...grpc.CallOption) (*ResolveAlertsResponse, error)
	// IntegrationStatus returns diagnostic checks for the caller's integration —
	// whether warehouses are bound, whether either queue is being drained, and
	// whether anything has been sitting in one for too long.
	IntegrationStatus(ctx context.Context, in *IntegrationStatusRequest, opts ...grpc.CallOption) (*IntegrationStatusResponse, error)
}

type fulfillmentIntegrationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFulfillmentIntegrationServiceClient(cc grpc.ClientConnInterface) FulfillmentIntegrationServiceClient {
	return &fulfillmentIntegrationServiceClient{cc}
}

func (c *fulfillmentIntegrationServiceClient) ListNeedToShip(ctx context.Context, in *ListNeedToShipRequest, opts ...grpc.CallOption) (*ListNeedToShipResponse, error) {
	out := new(ListNeedToShipResponse)
	err := c.cc.Invoke(ctx, "/shipping_api.FulfillmentIntegrationService/ListNeedToShip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fulfillmentIntegrationServiceClient) ListNeedToCancel(ctx context.Context, in *ListNeedToCancelRequest, opts ...grpc.CallOption) (*ListNeedToCancelResponse, error) {
	out := new(ListNeedToCancelResponse)
	err := c.cc.Invoke(ctx, "/shipping_api.FulfillmentIntegrationService/ListNeedToCancel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fulfillmentIntegrationServiceClient) GetFulfillmentOrder(ctx context.Context, in *GetFulfillmentOrderRequest, opts ...grpc.CallOption) (*FulfillmentOrder, error) {
	out := new(FulfillmentOrder)
	err := c.cc.Invoke(ctx, "/shipping_api.FulfillmentIntegrationService/GetFulfillmentOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fulfillmentIntegrationServiceClient) AcknowledgeFulfillmentOrders(ctx context.Context, in *AcknowledgeFulfillmentOrdersRequest, opts ...grpc.CallOption) (*AcknowledgeFulfillmentOrdersResponse, error) {
	out := new(AcknowledgeFulfillmentOrdersResponse)
	err := c.cc.Invoke(ctx, "/shipping_api.FulfillmentIntegrationService/AcknowledgeFulfillmentOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fulfillmentIntegrationServiceClient) ConfirmShipments(ctx context.Context, in *ConfirmShipmentsRequest, opts ...grpc.CallOption) (*ConfirmShipmentsResponse, error) {
	out := new(ConfirmShipmentsResponse)
	err := c.cc.Invoke(ctx, "/shipping_api.FulfillmentIntegrationService/ConfirmShipments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fulfillmentIntegrationServiceClient) ConfirmCancellations(ctx context.Context, in *ConfirmCancellationsRequest, opts ...grpc.CallOption) (*ConfirmCancellationsResponse, error) {
	out := new(ConfirmCancellationsResponse)
	err := c.cc.Invoke(ctx, "/shipping_api.FulfillmentIntegrationService/ConfirmCancellations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fulfillmentIntegrationServiceClient) RejectFulfillmentOrders(ctx context.Context, in *RejectFulfillmentOrdersRequest, opts ...grpc.CallOption) (*RejectFulfillmentOrdersResponse, error) {
	out := new(RejectFulfillmentOrdersResponse)
	err := c.cc.Invoke(ctx, "/shipping_api.FulfillmentIntegrationService/RejectFulfillmentOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fulfillmentIntegrationServiceClient) RaiseAlerts(ctx context.Context, in *RaiseAlertsRequest, opts ...grpc.CallOption) (*RaiseAlertsResponse, error) {
	out := new(RaiseAlertsResponse)
	err := c.cc.Invoke(ctx, "/shipping_api.FulfillmentIntegrationService/RaiseAlerts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fulfillmentIntegrationServiceClient) ResolveAlerts(ctx context.Context, in *ResolveAlertsRequest, opts ...grpc.CallOption) (*ResolveAlertsResponse, error) {
	out := new(ResolveAlertsResponse)
	err := c.cc.Invoke(ctx, "/shipping_api.FulfillmentIntegrationService/ResolveAlerts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fulfillmentIntegrationServiceClient) IntegrationStatus(ctx context.Context, in *IntegrationStatusRequest, opts ...grpc.CallOption) (*IntegrationStatusResponse, error) {
	out := new(IntegrationStatusResponse)
	err := c.cc.Invoke(ctx, "/shipping_api.FulfillmentIntegrationService/IntegrationStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FulfillmentIntegrationServiceServer is the server API for FulfillmentIntegrationService service.
// All implementations should embed UnimplementedFulfillmentIntegrationServiceServer
// for forward compatibility
type FulfillmentIntegrationServiceServer interface {
	// ListNeedToShip returns fulfillment orders you owe a shipment on: work
	// routed to your warehouses and not yet shipped or cancelled.
	//
	// New work and re-routed work look the same here, which is the point. A
	// partial re-route reduces a line's quantity rather than removing the
	// fulfillment order, so `lines` is authoritative on every read and must not
	// be cached across polls.
	//
	// An order leaves this queue when its lines are shipped, when Zentail
	// cancels it, or when you reject it. Acknowledging does not remove it — you
	// still owe the shipment.
	ListNeedToShip(context.Context, *ListNeedToShipRequest) (*ListNeedToShipResponse, error)
	// ListNeedToCancel returns fulfillment orders you have acknowledged that
	// Zentail now wants pulled back — re-routed to another warehouse, or
	// cancelled by the buyer or the channel.
	//
	// Only acknowledged work appears here. If you never told Zentail you had
	// created it, there is nothing on your side to undo and the units simply
	// leave ListNeedToShip.
	//
	// A partial cancellation puts the same fulfillment order in **both** queues:
	// cancel the quantities named here, ship what ListNeedToShip still shows.
	ListNeedToCancel(context.Context, *ListNeedToCancelRequest) (*ListNeedToCancelResponse, error)
	// GetFulfillmentOrder fetches one fulfillment order, whatever queue it is or
	// is not in. For troubleshooting and for reconciling after a crash.
	GetFulfillmentOrder(context.Context, *GetFulfillmentOrderRequest) (*FulfillmentOrder, error)
	// AcknowledgeFulfillmentOrders records the identifier you gave the work on
	// your own side. It does **not** drain ListNeedToShip — you still owe the
	// shipment — and it is not required before shipping.
	//
	// Two reasons to call it. It is how a crash between "created it on my side"
	// and "told Zentail" becomes recoverable: the fulfillment order is still in
	// ListNeedToShip, and the absence of your id there tells you to reconcile
	// before creating a duplicate. And it is what puts the work into
	// ListNeedToCancel if Zentail later needs it pulled back.
	AcknowledgeFulfillmentOrders(context.Context, *AcknowledgeFulfillmentOrdersRequest) (*AcknowledgeFulfillmentOrdersResponse, error)
	// ConfirmShipments reports packages that have shipped, draining the shipped
	// quantities from ListNeedToShip.
	//
	// Idempotent on external_shipment_id: replaying a shipment is a no-op, so a
	// retry after a timeout can never double-ship.
	ConfirmShipments(context.Context, *ConfirmShipmentsRequest) (*ConfirmShipmentsResponse, error)
	// ConfirmCancellations reports that you have pulled work back on your side,
	// draining it from ListNeedToCancel.
	//
	// Confirm only what you actually cancelled. If a unit has already shipped and
	// cannot be recalled, say so with `already_shipped` rather than confirming —
	// Zentail needs to know the difference to keep the customer order right.
	ConfirmCancellations(context.Context, *ConfirmCancellationsRequest) (*ConfirmCancellationsResponse, error)
	// RejectFulfillmentOrders tells Zentail you cannot fulfil work it asked for —
	// out of stock, damaged, address undeliverable. This is the other direction
	// from ConfirmCancellations: there, Zentail asked; here, you are declining.
	//
	// Zentail reroutes the work or surfaces it to the user, and it leaves
	// ListNeedToShip.
	RejectFulfillmentOrders(context.Context, *RejectFulfillmentOrdersRequest) (*RejectFulfillmentOrdersResponse, error)
	// RaiseAlerts raises alerts against fulfillment orders, using the same alert
	// model the rest of Zentail already shows on a customer order.
	//
	// Idempotent by design: Zentail refuses a second open alert of the same type
	// on the same order, so a poller can raise the same condition every pass
	// without creating noise. No client-side "have I already alerted?"
	// bookkeeping.
	//
	// An alert is not a substitute for rejecting. Raise one to explain a delay;
	// reject when you are not going to ship.
	RaiseAlerts(context.Context, *RaiseAlertsRequest) (*RaiseAlertsResponse, error)
	// ResolveAlerts resolves alerts **this integration raised**, recording why.
	//
	// Scoping matters: an alert of the same type raised by Zentail itself, or by
	// another integration, on the same order survives. Resolving by type alone
	// would let one caller silently clear another's alerts.
	ResolveAlerts(context.Context, *ResolveAlertsRequest) (*ResolveAlertsResponse, error)
	// IntegrationStatus returns diagnostic checks for the caller's integration —
	// whether warehouses are bound, whether either queue is being drained, and
	// whether anything has been sitting in one for too long.
	IntegrationStatus(context.Context, *IntegrationStatusRequest) (*IntegrationStatusResponse, error)
}

// UnimplementedFulfillmentIntegrationServiceServer should be embedded to have forward compatible implementations.
type UnimplementedFulfillmentIntegrationServiceServer struct {
}

func (UnimplementedFulfillmentIntegrationServiceServer) ListNeedToShip(context.Context, *ListNeedToShipRequest) (*ListNeedToShipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNeedToShip not implemented")
}
func (UnimplementedFulfillmentIntegrationServiceServer) ListNeedToCancel(context.Context, *ListNeedToCancelRequest) (*ListNeedToCancelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNeedToCancel not implemented")
}
func (UnimplementedFulfillmentIntegrationServiceServer) GetFulfillmentOrder(context.Context, *GetFulfillmentOrderRequest) (*FulfillmentOrder, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFulfillmentOrder not implemented")
}
func (UnimplementedFulfillmentIntegrationServiceServer) AcknowledgeFulfillmentOrders(context.Context, *AcknowledgeFulfillmentOrdersRequest) (*AcknowledgeFulfillmentOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcknowledgeFulfillmentOrders not implemented")
}
func (UnimplementedFulfillmentIntegrationServiceServer) ConfirmShipments(context.Context, *ConfirmShipmentsRequest) (*ConfirmShipmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmShipments not implemented")
}
func (UnimplementedFulfillmentIntegrationServiceServer) ConfirmCancellations(context.Context, *ConfirmCancellationsRequest) (*ConfirmCancellationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmCancellations not implemented")
}
func (UnimplementedFulfillmentIntegrationServiceServer) RejectFulfillmentOrders(context.Context, *RejectFulfillmentOrdersRequest) (*RejectFulfillmentOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectFulfillmentOrders not implemented")
}
func (UnimplementedFulfillmentIntegrationServiceServer) RaiseAlerts(context.Context, *RaiseAlertsRequest) (*RaiseAlertsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RaiseAlerts not implemented")
}
func (UnimplementedFulfillmentIntegrationServiceServer) ResolveAlerts(context.Context, *ResolveAlertsRequest) (*ResolveAlertsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveAlerts not implemented")
}
func (UnimplementedFulfillmentIntegrationServiceServer) IntegrationStatus(context.Context, *IntegrationStatusRequest) (*IntegrationStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IntegrationStatus not implemented")
}

// UnsafeFulfillmentIntegrationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FulfillmentIntegrationServiceServer will
// result in compilation errors.
type UnsafeFulfillmentIntegrationServiceServer interface {
	mustEmbedUnimplementedFulfillmentIntegrationServiceServer()
}

func RegisterFulfillmentIntegrationServiceServer(s grpc.ServiceRegistrar, srv FulfillmentIntegrationServiceServer) {
	s.RegisterService(&FulfillmentIntegrationService_ServiceDesc, srv)
}

func _FulfillmentIntegrationService_ListNeedToShip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNeedToShipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulfillmentIntegrationServiceServer).ListNeedToShip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shipping_api.FulfillmentIntegrationService/ListNeedToShip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulfillmentIntegrationServiceServer).ListNeedToShip(ctx, req.(*ListNeedToShipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FulfillmentIntegrationService_ListNeedToCancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNeedToCancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulfillmentIntegrationServiceServer).ListNeedToCancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shipping_api.FulfillmentIntegrationService/ListNeedToCancel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulfillmentIntegrationServiceServer).ListNeedToCancel(ctx, req.(*ListNeedToCancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FulfillmentIntegrationService_GetFulfillmentOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFulfillmentOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulfillmentIntegrationServiceServer).GetFulfillmentOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shipping_api.FulfillmentIntegrationService/GetFulfillmentOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulfillmentIntegrationServiceServer).GetFulfillmentOrder(ctx, req.(*GetFulfillmentOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FulfillmentIntegrationService_AcknowledgeFulfillmentOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeFulfillmentOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulfillmentIntegrationServiceServer).AcknowledgeFulfillmentOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shipping_api.FulfillmentIntegrationService/AcknowledgeFulfillmentOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulfillmentIntegrationServiceServer).AcknowledgeFulfillmentOrders(ctx, req.(*AcknowledgeFulfillmentOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FulfillmentIntegrationService_ConfirmShipments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmShipmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulfillmentIntegrationServiceServer).ConfirmShipments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shipping_api.FulfillmentIntegrationService/ConfirmShipments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulfillmentIntegrationServiceServer).ConfirmShipments(ctx, req.(*ConfirmShipmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FulfillmentIntegrationService_ConfirmCancellations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmCancellationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulfillmentIntegrationServiceServer).ConfirmCancellations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shipping_api.FulfillmentIntegrationService/ConfirmCancellations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulfillmentIntegrationServiceServer).ConfirmCancellations(ctx, req.(*ConfirmCancellationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FulfillmentIntegrationService_RejectFulfillmentOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectFulfillmentOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulfillmentIntegrationServiceServer).RejectFulfillmentOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shipping_api.FulfillmentIntegrationService/RejectFulfillmentOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulfillmentIntegrationServiceServer).RejectFulfillmentOrders(ctx, req.(*RejectFulfillmentOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FulfillmentIntegrationService_RaiseAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RaiseAlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulfillmentIntegrationServiceServer).RaiseAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shipping_api.FulfillmentIntegrationService/RaiseAlerts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulfillmentIntegrationServiceServer).RaiseAlerts(ctx, req.(*RaiseAlertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FulfillmentIntegrationService_ResolveAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveAlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulfillmentIntegrationServiceServer).ResolveAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shipping_api.FulfillmentIntegrationService/ResolveAlerts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulfillmentIntegrationServiceServer).ResolveAlerts(ctx, req.(*ResolveAlertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FulfillmentIntegrationService_IntegrationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntegrationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulfillmentIntegrationServiceServer).IntegrationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shipping_api.FulfillmentIntegrationService/IntegrationStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulfillmentIntegrationServiceServer).IntegrationStatus(ctx, req.(*IntegrationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FulfillmentIntegrationService_ServiceDesc is the grpc.ServiceDesc for FulfillmentIntegrationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FulfillmentIntegrationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shipping_api.FulfillmentIntegrationService",
	HandlerType: (*FulfillmentIntegrationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListNeedToShip",
			Handler:    _FulfillmentIntegrationService_ListNeedToShip_Handler,
		},
		{
			MethodName: "ListNeedToCancel",
			Handler:    _FulfillmentIntegrationService_ListNeedToCancel_Handler,
		},
		{
			MethodName: "GetFulfillmentOrder",
			Handler:    _FulfillmentIntegrationService_GetFulfillmentOrder_Handler,
		},
		{
			MethodName: "AcknowledgeFulfillmentOrders",
			Handler:    _FulfillmentIntegrationService_AcknowledgeFulfillmentOrders_Handler,
		},
		{
			MethodName: "ConfirmShipments",
			Handler:    _FulfillmentIntegrationService_ConfirmShipments_Handler,
		},
		{
			MethodName: "ConfirmCancellations",
			Handler:    _FulfillmentIntegrationService_ConfirmCancellations_Handler,
		},
		{
			MethodName: "RejectFulfillmentOrders",
			Handler:    _FulfillmentIntegrationService_RejectFulfillmentOrders_Handler,
		},
		{
			MethodName: "RaiseAlerts",
			Handler:    _FulfillmentIntegrationService_RaiseAlerts_Handler,
		},
		{
			MethodName: "ResolveAlerts",
			Handler:    _FulfillmentIntegrationService_ResolveAlerts_Handler,
		},
		{
			MethodName: "IntegrationStatus",
			Handler:    _FulfillmentIntegrationService_IntegrationStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shipping_api/fulfillment/service.proto",
}
